// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb75PKQ3jk9jkrVw0Y3DvITQw6vIq4rt4',
    appId: '1:1027682471808:web:a8d8cc54cc054f44c37b65',
    messagingSenderId: '1027682471808',
    projectId: 'auth-flutter-bloc-e0189',
    authDomain: 'auth-flutter-bloc-e0189.firebaseapp.com',
    storageBucket: 'auth-flutter-bloc-e0189.firebasestorage.app',
    measurementId: 'G-63FK6EZ215',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0RfRMDNzbrBPrcpp_9Ih3EW6Uqt1Iio',
    appId: '1:1027682471808:android:0eeced1cacb77db1c37b65',
    messagingSenderId: '1027682471808',
    projectId: 'auth-flutter-bloc-e0189',
    storageBucket: 'auth-flutter-bloc-e0189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4wmoczkO5xcfUsv6xmfuBZZF6Xsy1eg',
    appId: '1:1027682471808:ios:633dc701d9128582c37b65',
    messagingSenderId: '1027682471808',
    projectId: 'auth-flutter-bloc-e0189',
    storageBucket: 'auth-flutter-bloc-e0189.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd4wmoczkO5xcfUsv6xmfuBZZF6Xsy1eg',
    appId: '1:1027682471808:ios:633dc701d9128582c37b65',
    messagingSenderId: '1027682471808',
    projectId: 'auth-flutter-bloc-e0189',
    storageBucket: 'auth-flutter-bloc-e0189.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb75PKQ3jk9jkrVw0Y3DvITQw6vIq4rt4',
    appId: '1:1027682471808:web:ea1d63328ba7a4b2c37b65',
    messagingSenderId: '1027682471808',
    projectId: 'auth-flutter-bloc-e0189',
    authDomain: 'auth-flutter-bloc-e0189.firebaseapp.com',
    storageBucket: 'auth-flutter-bloc-e0189.firebasestorage.app',
    measurementId: 'G-61JW1JKXLV',
  );
}
